# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: 
 branches:
  include:
    - main
    - AMPTK_DEVELOPMENT_MASTER
    - AMPTK_STAGING_MASTER
    - AMPTK_PRODUCTION_MASTER
  exclude:
    - dev-remote  # Exclude the source branch used for PRs
    - feature/*   # Optionally exclude feature branches
    - bugfix/*    # Optionally exclude bugfix branches

pr:
  branches:
    include:
      - AMPTK_DEVELOPMENT_MASTER
      - AMPTK_STAGING_MASTER
      - AMPTK_PRODUCTION_MASTER

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.402'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go Dev/Test(7ea259f7-c666-4703-b4c1-df983f852504)'
    appType: 'webApp'
    WebAppName: 'it-job-finder'
    packageForLinux: '$(build.artifactStagingDirectory)/**/*.zip'