# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - it-job-finder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build Vue app
        run: |
          cd jobfinders.client
          npm install
          npm run build

      - name: Copy Vue build output to ASP.NET Core wwwroot
        run: |
          xcopy jobfinders.client/dist jobfinders.server/wwwroot /E /I /Y
  
      - name: Publish ASP.NET Core app
        run: dotnet publish JobFinders.server/JobFinders.Server.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: List downloaded files
        run: dir ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4CEE4A274D0A41BCA316BB942542D926 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2F923E111DF24A8DA2C763B4C8F18F77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE7CA4C7E8EB420CB18E3275205FC3D2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'it-job-finder'
          slot-name: 'Production'
          package: ./publish
